site_name: git
site_url: https://wumingsheng.github.io/mkdocs_git/

repo_url: https://github.com/wumingsheng/mkdocs_git


site_description: Git Project documentation with Markdown.
site_author: wumingsheng

edit_uri: ""





nav:
  - Home: index.md
  - Note: note.md
  - About: 
    - 独自使用git时的一些常见场景: about/stand-alone.md
theme: mkdocs
